// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MapDragController from "./map_drag_controller"
application.register("map-drag", MapDragController)

import MapSearchController from "./map_search_controller"
application.register("map-search", MapSearchController)
